#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QuizTime.Resource", IsApplication=true)]

namespace QuizTime
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorAsh = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimary = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryDark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ic_launcher_background = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int textColor = 2130771973;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int dvesti_dp = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int fifty_dp = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int sto_dp = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int subtitle = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int trista_dp = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int twenty_dp = 2130837509;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int correct = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int geography = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int history = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int sad = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int space = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int wrong = 2130903045;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int backToTopics = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int buttonSignIn = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int buttonSignUp = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int correctAnswerTextView = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int correctButton = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int drawerLayout = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int firstline = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int geographyLayout = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int goHomeButton = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int historyLayout = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int image = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int mainActivityPassword = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int mainActivityUsername = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int nextButton = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int optionARadio = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int optionATextView = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int optionBRadio = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int optionBTextView = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int optionCRadio = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int optionCTextView = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int optionDRadio = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int optionDTextView = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int proceedQuizButton = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int questionTextView = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int quizDescriptionText = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int quizImage = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int quizPositionTextView = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int quizTopicText = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int remarksTextView = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int scoreTextView = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int secondline = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int spaceLayout = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int startQuizButton = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int textInputEditTextName = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int textInputEditTextPassword = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int textInputEditTextPasswordAgain = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int textViewSignUp = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int timeCounterTextView = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int tv = 2130968614;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_main = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int completed = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int correct = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int gameMenu = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int include_main_page = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int quiz_page = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int selected_topic = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int signup = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int wrong = 2131034120;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int main_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_launcher = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_launcher_foreground = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_launcher_round = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F080000
			public const int Pyre = 2131230720;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int action_settings = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int click_on_me_for_music = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int enter_password = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int enter_password_again = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int enter_username = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int geography = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int go_home = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int history = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int incorrect_failed = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int login_or_create = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int next = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int ok = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int password = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int proceed = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int select_a_topic_for_quiz = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int sign_in = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int sign_up = 2131296273;
			
			// aapt resource value: 0x7F090012
			public const int space = 2131296274;
			
			// aapt resource value: 0x7F090013
			public const int username = 2131296275;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int topic_textView = 2131361793;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
